# Generated by Django 4.2.2 on 2023-07-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_train_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='seats',
        ),
        migrations.AddField(
            model_name='trainseat',
            name='train',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.train'),
            preserve_default=False,
        ),
    ]
