# Generated by Django 4.2.2 on 2023-07-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_train_seats_trainseat_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainreservation',
            name='reserved_seats',
        ),
        migrations.AddField(
            model_name='trainreservation',
            name='reserved_seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.trainseat'),
            preserve_default=False,
        ),
    ]
