# Generated by Django 4.2.2 on 2023-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='09052806897', max_length=12),
            preserve_default=False,
        ),
    ]
